services:
  # Apache and PHP service
  web:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - my-network
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html

  # MySQL service
  mysql:
    image: mysql:8.0
    restart: always
    networks:
      - my-network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agilecontent
      MYSQL_USER: diego
      MYSQL_PASSWORD: diego
    volumes:
      - mysql-data:/var/lib/mysql

  # phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    networks:
      - my-network
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql

# Define networks
networks:
  my-network:

volumes:
  appdata:
  mysql-data: